apiVersion: v1
kind: Service
metadata:
  name: payment-api
  namespace: monitoring
  labels:
    app: payment-api
spec:
  selector:
    app: payment-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
